-- ============================================
-- CATEGORIAS (+2 novas para totalizar lógica de 10 por seed)
-- ============================================
INSERT INTO categoria (id, nome, slug) VALUES
    (nextval('categoria_id_seq'), 'Tecnologia no Cotidiano', 'tecnologia-no-cotidiano'),
    (nextval('categoria_id_seq'), 'Seguranca Digital', 'seguranca-digital')
ON CONFLICT (slug) DO NOTHING;

-- ============================================
-- SERVIÇOS (10)
-- ============================================
INSERT INTO service (id, nome, descricao_curta, descricao_detalhada, problemas_que_resolve, beneficios, icone, cta_texto, cta_link, created_at)
VALUES
(nextval('service_id_seq'),
 'Criação de Sites Institucionais',
 'Sites profissionais e responsivos para sua empresa transmitir credibilidade online.',
 'Desenvolvemos sites institucionais completos com design moderno, responsivo e otimizado para mecanismos de busca. Seu site será a vitrine digital da sua empresa, transmitindo profissionalismo e gerando confiança nos seus clientes. Utilizamos as tecnologias mais recentes como React, Next.js e Spring Boot para garantir performance e segurança.',
 'Falta de presença digital | Site desatualizado e não responsivo | Baixa conversão de visitantes | Dificuldade em gerenciar conteúdo',
 'Design personalizado e moderno | Totalmente responsivo (mobile-first) | Otimizado para SEO (Google) | Painel administrativo intuitivo | Integração com redes sociais e WhatsApp',
 'Globe',
 'Solicitar Orçamento',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Desenvolvimento de Lojas Virtuais',
 'E-commerces completos, seguros e com alta taxa de conversão.',
 'Criamos lojas virtuais sob medida que vendem 24 horas por dia. Nossos e-commerces integram os principais meios de pagamento, calculam frete automaticamente e possuem painel de gestão de pedidos, estoque e clientes. Tudo com design focado em conversão e experiência do usuário.',
 'Loja virtual amadora com baixa conversão | Dificuldade em gerenciar pedidos e estoque | Falta de integração com marketplaces | Carrinho abandonado em excesso',
 'Integração com PagSeguro, Mercado Pago e Stripe | Cálculo automático de frete (Correios e transportadoras) | Painel completo de gestão | Recuperação de carrinho abandonado | Integração com Mercado Livre, Shopee e Amazon',
 'ShoppingCart',
 'Criar Minha Loja',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Aplicações Web Sob Medida',
 'Sistemas web personalizados para automatizar processos do seu negócio.',
 'Desenvolvemos sistemas web completos e personalizados para resolver problemas específicos do seu negócio. Seja um ERP, CRM, sistema de agendamento ou qualquer outra necessidade, nossa equipe analisa, projeta e desenvolve a solução ideal utilizando Java, Spring Boot, React e bancos de dados relacionais.',
 'Processos manuais e demorados | Falta de integração entre setores | Dificuldade em gerar relatórios | Dependência de planilhas Excel',
 'Automação de processos repetitivos | Dashboards com indicadores em tempo real | Controle de acesso por perfis de usuário | Escalável (cresce com seu negócio) | Suporte e manutenção contínuos',
 'Code',
 'Solicitar Demonstração',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Landing Pages de Alta Conversão',
 'Páginas otimizadas para campanhas, lançamentos e captura de leads.',
 'Criamos landing pages estrategicamente projetadas para converter visitantes em leads ou clientes. Cada elemento — título, copy, CTA, formulário e imagens — é pensado para maximizar a taxa de conversão da sua campanha de marketing digital.',
 'Baixa taxa de conversão em campanhas | Páginas genéricas sem foco | Dificuldade em capturar leads qualificados | Design que não converte',
 'Copywriting persuasivo | Design focado em conversão (CRO) | Formulários inteligentes | Integração com CRMs (RD Station, HubSpot) | Testes A/B para otimização contínua',
 'Target',
 'Quero Minha Landing Page',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Manutenção e Suporte de Websites',
 'Mantenha seu site sempre atualizado, seguro e funcionando perfeitamente.',
 'Oferecemos planos de manutenção contínua para garantir que seu site esteja sempre no ar, atualizado e protegido contra ameaças. Inclui atualizações de segurança, backups regulares, correção de bugs e pequenas melhorias sob demanda.',
 'Site fora do ar com frequência | Vulnerabilidades de segurança | Plugins e sistemas desatualizados | Lentidão e problemas de performance',
 'Monitoramento 24/7 | Backups automáticos diários | Atualizações de segurança | Correção rápida de bugs | Relatórios mensais de desempenho',
 'Wrench',
 'Ver Planos de Manutenção',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Otimização SEO (Search Engine Optimization)',
 'Apareça no topo do Google e atraia mais clientes organicamente.',
 'Realizamos auditoria completa de SEO e implementamos as melhores práticas para posicionar seu site nas primeiras posições do Google. Nosso trabalho inclui SEO técnico, otimização de conteúdo, link building e análise de concorrência.',
 'Baixo tráfego orgânico | Site não aparece no Google | Concorrentes sempre na frente | Conteúdo mal otimizado',
 'Auditoria completa de SEO | Otimização técnica (Core Web Vitals) | Pesquisa de palavras-chave | Criação de conteúdo otimizado | Relatórios mensais de posicionamento',
 'Search',
 'Auditar Meu Site',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Desenvolvimento de APIs REST',
 'APIs robustas e documentadas para integrar seus sistemas e aplicativos.',
 'Projetamos e desenvolvemos APIs RESTful escaláveis utilizando Java com Spring Boot. Nossas APIs são seguras (OAuth2/JWT), bem documentadas (OpenAPI/Swagger) e seguem as melhores práticas de mercado para integração entre sistemas.',
 'Sistemas que não se comunicam | Falta de documentação de APIs | APIs lentas e inseguras | Dificuldade em integrar com parceiros',
 'Documentação interativa com Swagger | Autenticação JWT e OAuth2 | Versionamento de endpoints | Alta performance e baixa latência | Testes automatizados',
 'Server',
 'Falar com Especialista',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Consultoria em Transformação Digital',
 'Orientaçao estratégica para digitalizar processos e modernizar seu negócio.',
 'Nossa consultoria analisa profundamente os processos atuais da sua empresa e propõe um roadmap de transformação digital. Identificamos oportunidades de automação, redução de custos e novas fontes de receita através da tecnologia.',
 'Processos analógicos e ineficientes | Resistência à mudança na equipe | Falta de visão estratégica digital | Desperdício de recursos',
 'Diagnóstico completo dos processos | Roadmap personalizado de transformação | Indicação das melhores tecnologias | Análise de custo-benefício | Acompanhamento da implantação',
 'Lightbulb',
 'Agendar Consultoria',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Migração de Sistemas Legados',
 'Modernize sistemas antigos sem perder dados e sem interromper operações.',
 'Migramos sistemas legados (desktop, mainframe, plataformas obsoletas) para a web com tecnologias modernas. Planejamos a migração de forma segura e gradual, garantindo zero perda de dados e mínima interrupção das operações do seu negócio.',
 'Sistema antigo sem suporte | Risco de perda de dados | Alto custo de manutenção | Incompatibilidade com novas tecnologias',
 'Migração segura e planejada | Zero perda de dados | Migração gradual (faseada) | Treinamento da equipe no novo sistema | Suporte durante a transição',
 'RefreshCw',
 'Modernizar Meu Sistema',
 '/contato',
 NOW()),

(nextval('service_id_seq'),
 'Criação de Portais Corporativos',
 'Portais internos para centralizar comunicação, documentos e processos da equipe.',
 'Desenvolvemos portais corporativos (intranets) que centralizam toda a comunicação interna, gestão de documentos, workflows de aprovação e dashboards da sua empresa. Tudo com acesso controlado por perfil e integrado aos seus sistemas existentes.',
 'Comunicação interna fragmentada | Documentos espalhados em e-mails e pastas | Falta de controle de acessos | Processos de aprovação lentos',
 'Central único de comunicação e documentos | Workflows de aprovação automatizados | Controle de acesso por perfil | Busca inteligente de documentos | Integração com Google Workspace e Microsoft 365',
 'Building2',
 'Solicitar Proposta',
 '/contato',
 NOW());

-- ============================================
-- POSTS DO BLOG (10)
-- ============================================
INSERT INTO post (id, titulo, slug, autor, imagem_capa, descricao, categoria_id, exibir_ao_publico, published_at, created_at)
VALUES
(nextval('post_id_seq'),
 'Por que sua empresa precisa de um site profissional em 2026',
 'por-que-sua-empresa-precisa-de-um-site-profissional-2026',
 'Equipe D3TEC',
 '/files/blog/site-profissional.jpg',
 'Ter um site profissional deixou de ser um diferencial e passou a ser uma necessidade básica para qualquer negócio. Neste artigo, exploramos os principais motivos pelos quais sua empresa não pode mais adiar essa decisão: credibilidade no mercado, alcance de novos clientes 24 horas por dia, fortalecimento da marca e aumento nas vendas. Apresentamos dados atualizados sobre o comportamento do consumidor digital brasileiro e como um site bem estruturado impacta diretamente no faturamento. Também abordamos os erros mais comuns ao criar um site e como evitá-los.',
 (SELECT id FROM categoria WHERE slug = 'dicas-para-negocios'),
 true,
 '2026-06-15 10:00:00',
 NOW()),

(nextval('post_id_seq'),
 'Como escolher a stack tecnológica ideal para o seu projeto web',
 'como-escolher-stack-tecnologica-ideal-projeto-web',
 'Equipe D3TEC',
 '/files/blog/stack-tecnologica.jpg',
 'A escolha da stack tecnológica é uma das decisões mais importantes no início de qualquer projeto de desenvolvimento web. Neste guia completo, comparamos as principais tecnologias do mercado: React vs Angular vs Vue no frontend, Node.js vs Java Spring Boot vs Python Django no backend, e PostgreSQL vs MongoDB no banco de dados. Analisamos critérios como curva de aprendizado, performance, escalabilidade, comunidade e custo de manutenção. Ao final, apresentamos uma matriz de decisão para ajudar você a escolher a stack ideal conforme o tipo e tamanho do seu projeto.',
 (SELECT id FROM categoria WHERE slug = 'desenvolvimento-web'),
 true,
 '2026-06-22 14:30:00',
 NOW()),

(nextval('post_id_seq'),
 'O guia completo de SEO para iniciantes: ranqueie no Google',
 'guia-completo-seo-iniciantes-ranqueie-google',
 'Equipe D3TEC',
 '/files/blog/guia-seo.jpg',
 'SEO pode parecer um bicho de sete cabeças para quem está começando, mas não precisa ser. Neste guia completo para iniciantes, explicamos de forma simples e prática os fundamentos do Search Engine Optimization: desde a escolha de palavras-chave até a otimização técnica do seu site. Abordamos SEO on-page (títulos, meta descriptions, headings), SEO off-page (link building, autoridade de domínio) e SEO técnico (velocidade de carregamento, mobile-first, Core Web Vitals). Inclui checklist prático para você aplicar imediatamente no seu site.',
 (SELECT id FROM categoria WHERE slug = 'dicas-para-negocios'),
 true,
 '2026-07-03 09:00:00',
 NOW()),

(nextval('post_id_seq'),
 'Landing Page vs Site Institucional: qual o melhor para o seu negócio?',
 'landing-page-vs-site-institucional-qual-melhor',
 'Equipe D3TEC',
 '/files/blog/landing-vs-site.jpg',
 'Muitos empreendedores ficam em dúvida entre criar uma landing page ou um site institucional completo. Cada formato atende a objetivos diferentes e entender isso é fundamental para investir o orçamento de marketing da forma certa. Neste artigo, comparamos os dois formatos em termos de objetivo, estrutura, custo, prazo de desenvolvimento e taxa de conversão. Explicamos quando usar cada um e também mostramos cases reais de clientes que obtiveram sucesso com a estratégia correta.',
 (SELECT id FROM categoria WHERE slug = 'desenvolvimento-web'),
 true,
 '2026-07-10 11:00:00',
 NOW()),

(nextval('post_id_seq'),
 'As 7 tendências de desenvolvimento web que vão dominar 2026',
 'tendencias-desenvolvimento-web-2026',
 'Equipe D3TEC',
 '/files/blog/tendencias-web-2026.jpg',
 'O mundo do desenvolvimento web evolui rapidamente e estar atualizado é essencial para se manter competitivo. Neste artigo, listamos as 7 principais tendências que estão moldando o mercado em 2026: WebAssembly ganhando espaço no frontend, a consolidação dos frameworks full-stack (Next.js, Remix), o uso crescente de IA generativa no desenvolvimento, a adoção de arquiteturas serverless, a evolução do CSS com Container Queries e View Transitions, a importância da acessibilidade digital, e a Web3 e aplicações descentralizadas. Para cada tendência, explicamos o que é, por que importa e como começar a adotar.',
 (SELECT id FROM categoria WHERE slug = 'inovacao'),
 true,
 '2026-07-17 08:00:00',
 NOW()),

(nextval('post_id_seq'),
 'Como uma Empresa Júnior pode impulsionar sua carreira em tecnologia',
 'empresa-junior-impulsionar-carreira-tecnologia',
 'Equipe D3TEC',
 '/files/blog/empresa-junior-carreira.jpg',
 'Participar de uma Empresa Júnior durante a faculdade é uma das experiências mais transformadoras para quem estuda tecnologia. Neste artigo, compartilhamos a história da D3TEC e como a vivência em EJ desenvolveu habilidades que a sala de aula não ensina: gestão de projetos reais, relacionamento com clientes, trabalho em equipe multidisciplinar, liderança e visão de negócio. Também damos dicas práticas para quem quer entrar em uma EJ ou fundar a sua própria, e depoimentos de ex-membros que hoje trabalham em grandes empresas de tecnologia.',
 (SELECT id FROM categoria WHERE slug = 'empresa-junior'),
 true,
 '2026-07-24 10:00:00',
 NOW()),

(nextval('post_id_seq'),
 'React ou Next.js: qual framework escolher para seu projeto?',
 'react-ou-nextjs-qual-framework-escolher',
 'Equipe D3TEC',
 '/files/blog/react-vs-nextjs.jpg',
 'React e Next.js são duas das tecnologias mais populares para desenvolvimento frontend, mas cada uma brilha em cenários diferentes. Neste comparativo técnico, exploramos as principais diferenças: renderização (CSR vs SSR vs SSG vs ISR), roteamento, otimização de imagens, performance de build, e ecossistema de plugins. Apresentamos também os custos de hospedagem, a complexidade de deploy (Vercel vs alternativas) e casos de uso ideais para cada um. Se você está começando um projeto novo ou migrando um existente, este artigo vai te ajudar a tomar a decisão certa.',
 (SELECT id FROM categoria WHERE slug = 'desenvolvimento-web'),
 true,
 '2026-07-28 15:00:00',
 NOW()),

(nextval('post_id_seq'),
 'A importância da manutenção contínua de sites e sistemas web',
 'importancia-manutencao-continua-sites-sistemas',
 'Equipe D3TEC',
 '/files/blog/manutencao-sites.jpg',
 'Lançar um site é apenas o começo. Sem manutenção contínua, seu site fica vulnerável a ataques, perde performance e pode até sair do ar. Neste artigo, explicamos por que a manutenção preventiva é mais barata que a corretiva e quais são os itens essenciais de um plano de manutenção: atualizações de segurança, backups, monitoramento de uptime, otimização de performance e atualização de conteúdo. Incluímos uma checklist de manutenção mensal que você pode aplicar hoje mesmo.',
 (SELECT id FROM categoria WHERE slug = 'dicas-para-negocios'),
 true,
 '2026-08-01 09:00:00',
 NOW()),

(nextval('post_id_seq'),
 'Metodologias ágeis na prática: como a D3TEC gerencia projetos',
 'metodologias-ageis-na-pratica-d3tec',
 'Equipe D3TEC',
 '/files/blog/metodologias-ageis.jpg',
 'Scrum, Kanban, sprints, daily meetings — você já ouviu esses termos mas sabe como aplicá-los na prática? Neste artigo, abrimos as portas da D3TEC e mostramos exatamente como gerenciamos nossos projetos de desenvolvimento web usando metodologias ágeis. Explicamos nosso fluxo de trabalho: da reunião de discovery com o cliente até a entrega final, passando por wireframes, protótipos, desenvolvimento iterativo e testes. Compartilhamos também as ferramentas que usamos (Jira, GitHub Projects, Figma) e as lições aprendidas ao longo de dezenas de projetos entregues.',
 (SELECT id FROM categoria WHERE slug = 'projetos-d3tec'),
 true,
 '2026-08-03 14:00:00',
 NOW()),

(nextval('post_id_seq'),
 'O que faz um desenvolvedor full-stack e como se tornar um',
 'o-que-faz-desenvolvedor-full-stack-como-se-tornar',
 'Equipe D3TEC',
 '/files/blog/desenvolvedor-fullstack.jpg',
 'O termo full-stack está em todo lugar, mas o que realmente significa? Neste artigo, desmistificamos o papel do desenvolvedor full-stack: as habilidades necessárias no frontend (HTML, CSS, JavaScript, React), no backend (Java, Node.js, bancos de dados), em DevOps (Docker, CI/CD) e em soft skills (comunicação, resolução de problemas). Traçamos um roadmap de estudos realista para quem quer entrar na área, com cursos, projetos práticos e certificações recomendadas. Inclui também uma análise do mercado de trabalho: salários, demanda e perspectivas para 2026 no Brasil.',
 (SELECT id FROM categoria WHERE slug = 'carreira-em-tecnologia'),
 true,
 '2026-08-04 10:00:00',
 NOW());

-- ============================================
-- CASES DE SUCESSO (10)
-- ============================================
INSERT INTO success_case (id, nome_projeto, cliente, descricao, imagem_capa, depoimento, exibir_ao_publico, featured, created_at)
VALUES
(nextval('success_case_id_seq'),
 'E-commerce D3 Moda',
 'D3 Moda',
 'Desenvolvemos uma loja virtual completa para a D3 Moda, uma confecção de moda feminina que buscava expandir suas vendas para todo o Brasil. O projeto incluiu catálogo com mais de 500 produtos organizados por categorias e coleções, integração com meios de pagamento (cartão, PIX e boleto), cálculo automático de frete pelos Correios, e painel administrativo completo para gestão de pedidos, estoque e clientes. O design foi pensado para mobile-first, já que 70% das clientes acessam por smartphone.',
 '/files/cases/d3moda.jpg',
 'A D3TEC transformou nosso negócio. Saímos de vendas apenas locais para entregar em todo o Brasil. O site é lindo, rápido e nossas clientes elogiam muito a experiência de compra. No primeiro mês já tivemos mais de 200 pedidos!',
 true,
 true,
 NOW()),

(nextval('success_case_id_seq'),
 'Portal Corporativo Grupo Almeida',
 'Grupo Almeida',
 'Criamos um portal corporativo (intranet) para o Grupo Almeida, holding com 5 empresas e mais de 300 colaboradores. O portal centraliza comunicados internos, gestão de documentos por departamento, workflow de aprovação de férias e reembolsos, calendário corporativo e dashboard de indicadores em tempo real. Implementamos controle de acesso granular por perfil (diretoria, gerência, operacional) e integração com o Active Directory para single sign-on.',
 '/files/cases/grupo-almeida.jpg',
 'Antes do portal, nossa comunicação interna era um caos: documentos se perdiam em e-mails, aprovações demoravam dias. A D3TEC entendeu exatamente nossas necessidades e entregou um sistema que realmente funciona. Reduzimos em 60% o tempo dos processos internos.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Landing Page Campanha Verão 2026',
 'Maré Viva Resort',
 'Desenvolvemos uma landing page de alta conversão para a campanha de verão do Maré Viva Resort. A página foi projetada com foco total em conversão: headline impactante, galeria de fotos imersiva, prova social com depoimentos de hóspedes, formulário de reserva simplificado e integração com WhatsApp para atendimento imediato. Também implementamos pixels de rastreamento do Facebook Ads e Google Ads para otimização das campanhas de mídia paga.',
 '/files/cases/mare-viva.jpg',
 'Investimos em anúncios no Instagram e Facebook, e a landing page que a D3TEC criou converteu 3x mais do que nosso site antigo. As reservas para o verão esgotaram um mês antes do previsto. Resultado incrível!',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Sistema de Gestão de Estoque',
 'Supermercado Bom Preço',
 'Desenvolvemos um sistema web de gestão de estoque sob medida para a rede de supermercados Bom Preço, com 4 lojas e mais de 10.000 itens no catálogo. O sistema controla entrada e saída de mercadorias, gera alertas automáticos de estoque baixo, sugere pedidos de reposição baseados no histórico de vendas, e integra com o ERP de frente de caixa. Implementamos também um módulo de inventário com leitura de código de barras via dispositivo móvel.',
 '/files/cases/bom-preco.jpg',
 'O sistema da D3TEC eliminou as planilhas de Excel que usávamos. Agora temos controle total do estoque em tempo real, reduzimos perdas por vencimento e conseguimos negociar melhor com fornecedores. O investimento se pagou em 4 meses.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Aplicativo de Delivery',
 'Sabor Caseiro',
 'Criamos um aplicativo web progressivo (PWA) de delivery para o restaurante Sabor Caseiro. O app funciona como nativo no celular (instalável na tela inicial), tem cardápio digital com fotos e descrições, carrinho de compras, integração com WhatsApp para confirmação de pedidos, e painel do restaurante para gerenciar pedidos em tempo real. Também implementamos geolocalização para cálculo de taxa de entrega por bairro.',
 '/files/cases/sabor-caseiro.jpg',
 'Nossos clientes adoraram o app! É muito mais prático que ligar ou mandar mensagem. O número de pedidos aumentou 40% e o ticket médio também subiu porque as fotos dos pratos estimulam a compra. E o melhor: não pagamos taxa de marketplace.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Site Institucional Prefeitura Municipal',
 'Prefeitura de São José do Rio Preto',
 'Desenvolvemos o novo site institucional para a Prefeitura Municipal com foco em transparência e acessibilidade digital. O portal conta com seção de notícias, agenda de eventos, portal da transparência com dados fiscais, carta de serviços ao cidadão, e ouvidoria online. Seguimos rigorosamente as diretrizes de acessibilidade WCAG 2.1 (nível AA) e a Lei de Acesso à Informação. O design é responsivo e atende aos padrões do gov.br.',
 '/files/cases/prefeitura.jpg',
 'A D3TEC entregou um portal muito acima das nossas expectativas. A população elogiou a facilidade de encontrar informações e os servidores acharam o painel administrativo muito intuitivo. Cumprimos todas as exigências legais de transparência.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Plataforma de Cursos Online',
 'Instituto Saber',
 'Desenvolvemos uma plataforma completa de ensino a distância (EAD) para o Instituto Saber. A plataforma inclui: área do aluno com trilha de aprendizado personalizada, player de vídeo com marcação de progresso, emissão automática de certificados em PDF, fórum de discussão por módulo, avaliações online com correção automática, e painel do professor para upload de conteúdo e acompanhamento de turmas. Toda a parte de pagamentos e matrículas também foi integrada.',
 '/files/cases/instituto-saber.jpg',
 'Nossa plataforma antiga vivia dando problema e os alunos reclamavam. A D3TEC construiu uma solução robusta do zero. Hoje temos mais de 2.000 alunos ativos, os certificados são emitidos automaticamente e o suporte técnico diminuiu drasticamente.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Dashboard de Vendas em Tempo Real',
 'Atacadão do Brás',
 'Criamos um dashboard de Business Intelligence em tempo real para a diretoria comercial do Atacadão do Brás. O painel consolida dados de vendas de 12 filiais, apresentando métricas como faturamento por loja, ticket médio, produtos mais vendidos, performance por vendedor e meta vs realizado. Os dados são atualizados a cada 5 minutos via integração com o ERP da empresa. Também implementamos alertas automáticos via e-mail e WhatsApp quando metas estão abaixo do esperado.',
 '/files/cases/atacadao-bras.jpg',
 'Antes, a diretoria esperava até o fim do mês para ver os relatórios. Com o dashboard da D3TEC, tomamos decisões em tempo real. Já identificamos e corrigimos problemas de estoque que teriam causado perda de vendas. A interface é tão intuitiva que até quem não é de tecnologia usa sem dificuldade.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Marketplace de Serviços Locais',
 'ServiFácil',
 'Desenvolvemos um marketplace web que conecta prestadores de serviços locais (eletricistas, encanadores, pintores, diaristas) a clientes. A plataforma inclui: cadastro e verificação de profissionais, sistema de orçamento online, agendamento de serviços, avaliação e reputação dos profissionais, chat integrado entre cliente e prestador, e sistema de pagamento seguro que libera o valor somente após a conclusão do serviço. O design é neutro e intuitivo para atender públicos de todas as idades.',
 '/files/cases/servifacil.jpg',
 'A D3TEC entendeu perfeitamente o conceito do nosso negócio. O marketplace ficou exatamente como imaginávamos — e melhor. Em 6 meses já temos mais de 500 profissionais cadastrados e 3.000 serviços realizados. A funcionalidade de pagamento seguro foi o grande diferencial para os clientes.',
 true,
 false,
 NOW()),

(nextval('success_case_id_seq'),
 'Rede Social para Profissionais de Saúde',
 'Saúde Conectada',
 'Criamos uma rede social exclusiva para profissionais e estudantes da área da saúde. A plataforma permite criar perfil profissional detalhado com especialidades, publicar e comentar artigos científicos, participar de grupos de discussão por especialidade, seguir outros profissionais, e receber feed personalizado de conteúdos relevantes. Implementamos moderação de conteúdo com IA para garantir a qualidade das publicações e verificação de registro profissional (CRM, Coren, etc.) para validação de perfis.',
 '/files/cases/saude-conectada.jpg',
 'Existia uma lacuna enorme: não havia uma rede social séria e focada para profissionais de saúde. A D3TEC criou exatamente o que o mercado precisava. A verificação de CRM foi essencial para dar credibilidade. Hoje somos a maior comunidade de saúde do Brasil, com mais de 50.000 profissionais ativos.',
 true,
 false,
 NOW());

-- ============================================
-- PARCEIROS (10)
-- ============================================
INSERT INTO partner (id, nome, logo, link, tipo, ativo, autorizacao_exibicao, created_at)
VALUES
(nextval('partner_id_seq'), 'RD Station', '/files/partners/rdstation.png', 'https://www.rdstation.com', 'TECNOLOGIA', true, true, NOW()),
(nextval('partner_id_seq'), 'VTEX', '/files/partners/vtex.png', 'https://vtex.com', 'TECNOLOGIA', true, true, NOW()),
(nextval('partner_id_seq'), 'Mercado Pago', '/files/partners/mercadopago.png', 'https://www.mercadopago.com.br', 'TECNOLOGIA', true, true, NOW()),
(nextval('partner_id_seq'), 'AWS Activate', '/files/partners/aws.png', 'https://aws.amazon.com', 'TECNOLOGIA', true, true, NOW()),
(nextval('partner_id_seq'), 'GitHub', '/files/partners/github.png', 'https://github.com', 'TECNOLOGIA', true, true, NOW()),
(nextval('partner_id_seq'), 'Brasil Júnior', '/files/partners/brasil-junior.png', 'https://www.brasiljunior.org.br', 'INSTITUCIONAL', true, true, NOW()),
(nextval('partner_id_seq'), 'Sebrae', '/files/partners/sebrae.png', 'https://www.sebrae.com.br', 'INSTITUCIONAL', true, true, NOW()),
(nextval('partner_id_seq'), 'Núcleo de Inovação UFRN', '/files/partners/nucleo-ufrn.png', 'https://www.ufrn.br', 'INSTITUCIONAL', true, true, NOW()),
(nextval('partner_id_seq'), 'Assespro', '/files/partners/assespro.png', 'https://assespro.org.br', 'INSTITUCIONAL', true, true, NOW()),
(nextval('partner_id_seq'), 'D3 Moda', '/files/partners/d3moda.png', 'https://www.d3moda.com.br', 'CLIENTE', true, true, NOW());

-- ============================================
-- INDICADORES (10)
-- ============================================
INSERT INTO indicador (id, nome, valor, descricao, created_at)
VALUES
(nextval('indicador_id_seq'), 'Projetos Entregues', '250+', 'Sites, sistemas e aplicações desenvolvidos e entregues com sucesso desde a fundação.', NOW()),
(nextval('indicador_id_seq'), 'Clientes Atendidos', '180+', 'Empresas e empreendedores que confiaram na D3TEC para sua presença digital.', NOW()),
(nextval('indicador_id_seq'), 'Anos de Experiência', '8+', 'Anos de atuação no mercado de desenvolvimento web e transformação digital.', NOW()),
(nextval('indicador_id_seq'), 'Horas de Desenvolvimento', '50.000+', 'Horas acumuladas de código, design e gestão de projetos pela nossa equipe.', NOW()),
(nextval('indicador_id_seq'), 'Sites no Ar', '320+', 'Sites e portais atualmente online e funcionando para nossos clientes.', NOW()),
(nextval('indicador_id_seq'), 'Lojas Virtuais', '45+', 'E-commerces desenvolvidos com foco em conversão e experiência do usuário.', NOW()),
(nextval('indicador_id_seq'), 'Desenvolvedores na Equipe', '30+', 'Profissionais dedicados entre devs, designers, QA e gestores de projeto.', NOW()),
(nextval('indicador_id_seq'), 'Parcerias Tecnológicas', '20+', 'Parcerias estratégicas com as principais plataformas e ferramentas do mercado.', NOW()),
(nextval('indicador_id_seq'), 'Taxa de Satisfação', '98%', 'Percentual de clientes satisfeitos com os projetos entregues (pesquisa NPS).', NOW()),
(nextval('indicador_id_seq'), 'Cidades Atendidas', '60+', 'Municípios brasileiros onde já entregamos projetos de desenvolvimento web.', NOW());

-- ============================================
-- MENSAGENS DE CONTATO (10)
-- ============================================
INSERT INTO contact_message (id, nome, email, telefone, empresa, endereco, assunto, mensagem, created_at)
VALUES
(nextval('contact_message_seq_generator'),
 'Roberto Almeida',
 'roberto.almeida@email.com',
 '(11) 98765-4321',
 'Construtora Almeida Ltda',
 'Av. Paulista, 1000 - São Paulo/SP',
 'Orçamento de site institucional',
 'Olá, gostaria de solicitar um orçamento para criação do site institucional da nossa construtora. Precisamos de um site moderno, responsivo, com área de empreendimentos, formulário de contato e integração com WhatsApp. Nosso prazo é de 45 dias. Aguardo contato.',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Fernanda Costa',
 'fernanda@modaonline.com.br',
 '(21) 99876-5432',
 'Moda Online',
 'Rua das Laranjeiras, 500 - Rio de Janeiro/RJ',
 'Desenvolvimento de e-commerce',
 'Tenho uma loja de roupas e acessórios e quero criar uma loja virtual completa. Preciso de catálogo de produtos, integração com meios de pagamento, cálculo de frete e um painel para gerenciar pedidos. Qual o prazo e investimento aproximado?',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Marcos Vinícius',
 'marcos@techconsult.com.br',
 '(31) 93456-7890',
 'TechConsult',
 'Av. Afonso Pena, 2000 - Belo Horizonte/MG',
 'Consultoria em transformação digital',
 'Somos uma consultoria e temos um cliente do setor industrial que precisa digitalizar seus processos. Gostaria de agendar uma reunião para discutirmos uma possível parceria nesse projeto. Podemos conversar essa semana?',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Juliana Santos',
 'juliana@lancamentosdigitais.com',
 '(47) 99123-4567',
 'Lançamentos Digitais',
 'Rua XV de Novembro, 300 - Blumenau/SC',
 'Landing page para campanha de lançamento',
 'Estou preparando o lançamento de um infoproduto para o próximo mês e preciso de uma landing page de alta conversão. A página precisa ter headline persuasiva, seção de benefícios, prova social, formulário de checkout e pixel de rastreamento. É urgente!',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Carlos Eduardo',
 'cadu@restaurantebomgosto.com',
 '(85) 98877-6655',
 'Restaurante Bom Gosto',
 'Av. Beira Mar, 1500 - Fortaleza/CE',
 'Manutenção de site existente',
 'Nosso site atual está muito lento e vive caindo. Foi feito por um freela há 3 anos e nunca mais recebeu manutenção. Preciso de um plano de manutenção urgente e talvez um redesign. Vocês podem fazer uma análise e me enviar uma proposta?',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Patrícia Oliveira',
 'patricia@clinicasorriso.com',
 '(61) 97654-3210',
 'Clínica Sorriso',
 'SHS Quadra 6 - Brasília/DF',
 'Criação de aplicativo de agendamento',
 'Somos uma rede de clínicas odontológicas com 8 unidades e precisamos de um sistema web de agendamento de consultas. Os pacientes precisam conseguir agendar online, receber confirmação por WhatsApp e e-mail, e as secretárias precisam de um painel de gestão. É possível?',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Gustavo Henrique',
 'gustavo@sistemaslegados.com',
 '(51) 95544-3322',
 'Indústria Metalúrgica Gaúcha',
 'Rodovia BR-116, Km 300 - Caxias do Sul/RS',
 'Migração de sistema legado',
 'Temos um sistema desktop em Delphi que gerencia toda nossa produção há 15 anos. Precisamos migrar para web com urgência porque não encontramos mais desenvolvedores Delphi. O sistema tem cerca de 200 funcionalidades. Vocês têm experiência nesse tipo de migração?',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Amanda Ribeiro',
 'amanda@agenciaup.com.br',
 '(41) 98899-0011',
 'Agência Up',
 'Rua Marechal Deodoro, 800 - Curitiba/PR',
 'Parceria tecnológica - SEO',
 'Somos uma agência de marketing digital e estamos buscando um parceiro de tecnologia para a parte de SEO técnico dos sites dos nossos clientes. Vocês teriam interesse em uma parceria de white label? Temos 15 clientes ativos nessa demanda.',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Ricardo Nunes',
 'ricardo@startupapp.com',
 '(19) 96789-0123',
 'App Fácil',
 'Av. Cambuí, 450 - Campinas/SP',
 'Desenvolvimento de API REST',
 'Nossa startup está desenvolvendo um app mobile e precisamos de uma API REST robusta para o backend. A API precisa ter autenticação JWT, upload de imagens, push notifications e integração com gateways de pagamento. Vocês trabalham com Java Spring Boot? Nos mandem uma proposta.',
 NOW()),

(nextval('contact_message_seq_generator'),
 'Larissa Mendes',
 'larissa@colegiofuturo.edu.br',
 '(81) 93210-4567',
 'Colégio Futuro',
 'Av. Boa Viagem, 2000 - Recife/PE',
 'Portal do aluno e responsável',
 'Precisamos de um portal online para nosso colégio onde pais e alunos possam consultar notas, frequência, boletos, calendário escolar e se comunicar com os professores. São cerca de 1.200 alunos. Também queremos um app mobile. Nos enviem uma apresentação comercial e valores.',
 NOW());
